server:
  port: 9081
spring:
  application:
      name: ${APP_NAME:ms-eventos}
  datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      password: ${DB_PASSWORD:admin}
      url: jdbc:oracle:thin:@192.168.0.102:30011/XEPDB1
      username: ${DB_USERNAME:inscrip_admin}
  jpa:
      hibernate:
          ddl-auto: update
      properties:
          hibernate:
              dialect: org.hibernate.dialect.OracleDialect
      show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true